/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Technician;

import javax.swing.JPanel;

/**
 *
 * @author shrey
 */
public class TechnicianHomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TechnicianHomeJPanel
     */
    
    JPanel jpanel19;
    
    public TechnicianHomeJPanel(JPanel techHome) {
        initComponents();
        
        this.TechHomeJPanel = techHome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TechHomeJPanel = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        TechHomeJPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout TechHomeJPanelLayout = new javax.swing.GroupLayout(TechHomeJPanel);
        TechHomeJPanel.setLayout(TechHomeJPanelLayout);
        TechHomeJPanelLayout.setHorizontalGroup(
            TechHomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 869, Short.MAX_VALUE)
        );
        TechHomeJPanelLayout.setVerticalGroup(
            TechHomeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );

        add(TechHomeJPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TechHomeJPanel;
    // End of variables declaration//GEN-END:variables
}
