/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Resident;

import UI.MainJPanel;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.AnalyticsUtil;
import models.DB4OUtil.DB4OUtil;
import models.EcoSystem;
import models.User.Customer.Resident;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.statistics.HistogramDataset;

/**
 *
 * CODE CITATION AND REFERENCE - https://www.youtube.com/watch?v=HviIu-9i1BU&t=2008s
 */
public class IndiProfileDashboard extends javax.swing.JPanel {

    /**
     * Creates new form IndiProfileDetailsJPanel
     */
    
    JPanel jpanel3;
    EcoSystem ecosystem;
    Resident resident;
    public IndiProfileDashboard(JPanel JPanelIndiLogin, EcoSystem ecosystem, Resident resident) {
        initComponents();
        
        this.indidashboard = JPanelIndiLogin;
        this.ecosystem = ecosystem;
        this.resident = resident;
        nameLabel.setText(resident.getFullName());
        rewardsLbl.setText(String.valueOf(resident.getRewardPoints()));
        showBarChart();
//        showHistogram();
        showPieChart();
        showBarChartTotalEWaste();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indidashboard = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        barPlotPanel = new javax.swing.JPanel();
        piePlotPanel = new javax.swing.JPanel();
        RewardPointsPanel = new javax.swing.JPanel();
        HistogramPlotPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rewardsLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        indidashboard.setBackground(new java.awt.Color(255, 255, 255));
        indidashboard.setPreferredSize(new java.awt.Dimension(1460, 850));

        kGradientPanel1.setkEndColor(new java.awt.Color(198, 226, 233));
        kGradientPanel1.setkGradientFocus(800);
        kGradientPanel1.setkStartColor(new java.awt.Color(167, 190, 211));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(300, 1460));

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Welcome to ReQube,");

        nameLabel.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(51, 51, 51));

        logoutBtn.setBackground(new java.awt.Color(205, 223, 245));
        logoutBtn.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(51, 51, 51));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_rounded_left_50px.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(null);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                        .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backarrow.png"))); // NOI18N
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnBack.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        barPlotPanel.setBackground(new java.awt.Color(255, 255, 255));
        barPlotPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        barPlotPanel.setLayout(new javax.swing.BoxLayout(barPlotPanel, javax.swing.BoxLayout.LINE_AXIS));

        piePlotPanel.setBackground(new java.awt.Color(255, 255, 255));
        piePlotPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        piePlotPanel.setLayout(new javax.swing.BoxLayout(piePlotPanel, javax.swing.BoxLayout.LINE_AXIS));

        RewardPointsPanel.setBackground(new java.awt.Color(255, 255, 255));
        RewardPointsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout RewardPointsPanelLayout = new javax.swing.GroupLayout(RewardPointsPanel);
        RewardPointsPanel.setLayout(RewardPointsPanelLayout);
        RewardPointsPanelLayout.setHorizontalGroup(
            RewardPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );
        RewardPointsPanelLayout.setVerticalGroup(
            RewardPointsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        HistogramPlotPanel.setBackground(new java.awt.Color(255, 255, 255));
        HistogramPlotPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        HistogramPlotPanel.setLayout(new javax.swing.BoxLayout(HistogramPlotPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("My Rewards");

        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(51, 51, 51)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prize_96px.png"))); // NOI18N

        rewardsLbl.setBackground(new java.awt.Color(255, 255, 255));
        rewardsLbl.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        rewardsLbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(198, 226, 233), 3, true));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 28)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Points");

        javax.swing.GroupLayout indidashboardLayout = new javax.swing.GroupLayout(indidashboard);
        indidashboard.setLayout(indidashboardLayout);
        indidashboardLayout.setHorizontalGroup(
            indidashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1588, Short.MAX_VALUE)
            .addGroup(indidashboardLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(indidashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indidashboardLayout.createSequentialGroup()
                        .addComponent(barPlotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(piePlotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addGroup(indidashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(indidashboardLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGroup(indidashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(indidashboardLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(indidashboardLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(rewardsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(indidashboardLayout.createSequentialGroup()
                        .addGroup(indidashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HistogramPlotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addComponent(RewardPointsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(384, 384, 384))))
        );
        indidashboardLayout.setVerticalGroup(
            indidashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indidashboardLayout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(indidashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indidashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(piePlotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(barPlotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(indidashboardLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(indidashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(indidashboardLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(indidashboardLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(rewardsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(indidashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indidashboardLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(HistogramPlotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(indidashboardLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(RewardPointsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        add(indidashboard, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        
        MainJPanel main = new MainJPanel(indidashboard);
        CardLayout layout = (CardLayout) indidashboard.getLayout();
        indidashboard.add("Home", main);

        layout.next(indidashboard);

        DB4OUtil.getInstance().storeSystem(this.ecosystem);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        indidashboard.remove(this);
        CardLayout layout = (CardLayout) indidashboard.getLayout();
        layout.previous(indidashboard);
    }//GEN-LAST:event_btnBackActionPerformed
    
   
    
    
    public void showPieChart(){
        
        //create dataset
      DefaultPieDataset barDataset = new DefaultPieDataset( );
      barDataset.setValue( "Refurbished" , AnalyticsUtil.individualRefurbCount(ecosystem, resident) );  
      barDataset.setValue( "Recycled" , AnalyticsUtil.individualRecycleCount(ecosystem, resident));   
 
      
      //create chart
       JFreeChart piechart = ChartFactory.createPieChart("Where did your E-Waste go?",barDataset, false,true,false);//explain
      
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
       //changing pie chart blocks colors
       piePlot.setSectionPaint("Refurbished", new Color(128, 155, 206));
        piePlot.setSectionPaint("Recycled", new Color(149, 184, 209));

       
        piePlot.setBackgroundPaint(Color.white);
        
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        piePlotPanel.removeAll();
        piePlotPanel.add(barChartPanel, BorderLayout.CENTER);
        piePlotPanel.validate();
    }

    
    public void showBarChart(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        HashMap<String, Integer> contribMap = AnalyticsUtil.individualContributionByCategory(ecosystem, resident);
        // Set value takes 3 param -> (count, Y axis name, X axis name)
        dataset.setValue(contribMap.get("Home Appliances"), "Total", "Home Appliances");
        dataset.setValue(contribMap.get("Communications & IT Devices"), "Total", "Communications & IT Devices");
        dataset.setValue(contribMap.get("Office and Medical Equipment"), "Total", "Office and Medical Equipment");
        dataset.setValue(contribMap.get("Home Entertainment Devices"), "Total", "Home Entertainment Devices");
        dataset.setValue(contribMap.get("Electronic Utilities"), "Total", "Electronic Utilities");
        dataset.setValue(contribMap.get("Others"), "Total", "Others");
        
        JFreeChart chart = ChartFactory.createBarChart("Last Contribution","E-waste Types","Total", 
                dataset, PlotOrientation.VERTICAL, false,true,false);
        
        CategoryPlot categoryPlot = chart.getCategoryPlot();
        //categoryPlot.setRangeGridlinePaint(Color.BLUE);
        categoryPlot.setBackgroundPaint(Color.WHITE);
        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        Color clr3 = new Color(167,190,211);
        renderer.setSeriesPaint(0, clr3);
        
        ChartPanel barpChartPanel = new ChartPanel(chart);
        barPlotPanel.removeAll();
        barPlotPanel.add(barpChartPanel, BorderLayout.CENTER);
        barPlotPanel.validate();
        
        
    }
    
    public void showBarChartTotalEWaste(){
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        
        // Set value takes 3 param -> (count, Y axis name, X axis name)
        dataset.setValue(200, "Total", "january");
        dataset.setValue(150, "Total", "february");
        dataset.setValue(18, "Total", "march");
        dataset.setValue(100, "Total", "april");
        dataset.setValue(80, "Total", "may");
        dataset.setValue(250, "Total", "june");
        
        JFreeChart chart = ChartFactory.createBarChart("Total E-Waste Contributed","monthly","Total", 
                dataset, PlotOrientation.VERTICAL, false,true,false);
        
        CategoryPlot categoryPlot = chart.getCategoryPlot();
        //categoryPlot.setRangeGridlinePaint(Color.BLUE);
        categoryPlot.setBackgroundPaint(Color.WHITE);
        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        Color clr3 = new Color(167,190,211);
        renderer.setSeriesPaint(0, clr3);
        
        ChartPanel barpChartPanel = new ChartPanel(chart);
        HistogramPlotPanel.removeAll();
        HistogramPlotPanel.add(barpChartPanel, BorderLayout.CENTER);
        HistogramPlotPanel.validate();
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HistogramPlotPanel;
    private javax.swing.JPanel RewardPointsPanel;
    private javax.swing.JPanel barPlotPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel indidashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel piePlotPanel;
    private javax.swing.JLabel rewardsLbl;
    // End of variables declaration//GEN-END:variables
}
